Array Stacking or Joining

In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])

In [7]:
# vertical stacking
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# horizontal stack
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# column stack 
np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])