Numpy Array Intersection and Difference

In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])

In [4]:
# intersection
np.intersect1d(n1,n2)

array([4, 5, 6])

In [5]:
# differece 
# ekiminates common elements from n1
np.setdiff1d(n1,n2)

array([1, 2, 3])

In [6]:
# differece 
# ekiminates common elements from n2
np.setdiff1d(n2,n1)

array([7, 8, 9])