In [1]:
import numpy as np

In [6]:
n1 = np.array([10,20,30,40])

In [10]:
# this adds 1 to all the elements
n2 = n1+1
n2

array([11., 21., 31., 41.])

In [12]:
# similarly sub
n3 = n1-1
n3


array([ 9., 19., 29., 39.])

In [13]:
# similarly mul
n4 = n1*2
n4

array([20., 40., 60., 80.])

In [14]:
# similarly div
n5 = n1/2
n5

array([ 5., 10., 15., 20.])