NumPy basics

In [5]:
import numpy as np

In [6]:
#creating one dimentional numpy array
n1 = np.array([1,2,3,4,5,6])
n1

array([1, 2, 3, 4, 5, 6])

In [7]:
#creating multi dimentional numpy array
n2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[11,12,13,14]])
n2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [11, 12, 13, 14]])

In [7]:
type(n1)
type(n2)

numpy.ndarray

In [11]:
# creating zero array
n0 = np.zeros((13,13))

In [12]:
n0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# creating a numpy array wit same array
n3 = np.full((5,5),6)
n3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [19]:
# tested for string  array
n4 = np.full((2,2),"five")
n4

array([['five', 'five'],
       ['five', 'five']], dtype='<U4')

In [20]:
# creating numpy array using range
n5 = np.arange(10,50,5)
n5
# here the parameters are start , end , increments resprectively

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
# creating a random numpy array
n6 = np.random.randint(1,100,10)
n6
# here the parameters are between 1 and 100 and 10 numbers

array([33, 46, 41, 83, 20, 90, 32, 91, 55, 15])

In [25]:
# check the shape of a numpy array
n6.shape

(10,)

In [27]:
# change the shape of numpy array
n6.shape = (2,5)
n6

array([[33, 46, 41, 83, 20],
       [90, 32, 91, 55, 15]])

In [28]:
#checking the shape again
n6.shape

(2, 5)

In [31]:
# testing shape attribute for range array
n5 = np.arange(10,50,5)
n5.shape = (2,4)
n5

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])